name: "Build"
on:
  push:
    branches:
      - master
      - next
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - cloud
          - live
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          # Live
          sudo apt-get install -y \
              debootstrap \
              squashfs-tools \
              xorriso \
              isolinux \
              syslinux-efi \
              grub-pc-bin \
              grub-efi-amd64-bin \
              grub-efi-ia32-bin \
              mtools \
              dosfstools
          # Cloud
          sudo apt-get install -y \
            debootstrap \
            arch-install-scripts \
            qemu-utils \
            libguestfs-tools
      - run: |
          sudo make ${{ matrix.profile }}
      - run: |
          pipx install b2
      - run: |
          b2v4 sync \
             --keep-days 90 \
             --replace-newer \
             ./src/${{ matrix.profile }}/dist/ \
             b2://images-service-slvn-co/images/${{ matrix.profile }}/
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
