name: "Build"
on:
  push:
    branches:
      - master
      - next
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
          - cloud
          - live
        version:
          - trixie
        include:
          - profile: cloud
            setup: |
              sudo apt-get update
              sudo apt-get install -y \
                debootstrap \
                arch-install-scripts \
                qemu-utils \
                libguestfs-tools
          - profile: live
            setup: |
              sudo apt-get update
              sudo apt-get install -y \
                  debootstrap \
                  squashfs-tools \
                  xorriso \
                  isolinux \
                  syslinux-efi \
                  grub-pc-bin \
                  grub-efi-amd64-bin \
                  grub-efi-ia32-bin \
                  mtools \
                  dosfstools
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ${{ matrix.setup }}
      - run: |
          sudo SLVN_VERSION=${{ matrix.version }} make ${{ matrix.profile }}
      - run: |
          pipx install b2
      - run: |
          b2v4 sync \
             --keep-days 90 \
             --replace-newer \
             ./src/${{ matrix.profile }}/dist/ \
             b2://images-service-slvn-co/images/${{ matrix.profile }}/${{ matrix.version }}
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
